# Generated by Django 2.2 on 2019-07-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolycomIpPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_ip', models.CharField(max_length=30)),
                ('mac_address', models.CharField(max_length=20)),
                ('time_stamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Call_details',
            fields=[
                ('polycomipphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pull.PolycomIpPhone')),
                ('call_reference', models.CharField(max_length=10)),
                ('call_state', models.CharField(max_length=10)),
                ('call_type', models.CharField(max_length=20)),
                ('UI_Appearance_Index', models.CharField(max_length=5)),
                ('called_party_name', models.SlugField()),
                ('called_party_dir_num', models.SlugField()),
                ('calling_party_name', models.CharField(max_length=20)),
                ('calling_party_dir_num', models.TextField()),
                ('call_duration', models.IntegerField(null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('muted', models.IntegerField(null=True)),
                ('ringing', models.IntegerField(null=True)),
            ],
            bases=('pull.polycomipphone',),
        ),
        migrations.CreateModel(
            name='On_Off_hook',
            fields=[
                ('polycomipphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pull.PolycomIpPhone')),
                ('line_num', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            bases=('pull.polycomipphone',),
        ),
    ]
