# Generated by Django 2.2 on 2019-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0005_auto_20190718_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_details',
            name='called_party_dir_num',
            field=models.TextField(null=True),
        ),
    ]
