# Generated by Django 2.2 on 2019-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0006_auto_20190718_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polycomipphone',
            name='time_stamp',
            field=models.DateTimeField(verbose_name='time called'),
        ),
    ]
