# Generated by Django 2.2 on 2019-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0007_auto_20190719_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polycomipphone',
            name='phone_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='polycomipphone',
            name='time_stamp',
            field=models.DateTimeField(null=True, verbose_name='time called'),
        ),
    ]
