# Generated by Django 2.2 on 2019-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0008_auto_20190722_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polycomipphone',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
