# Generated by Django 2.2 on 2019-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull', '0010_auto_20190722_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polycomipphone',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
